// Course Types
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const SWITCH_PAGE = 'SWITCH_PAGE';

// SignUpLogIn Types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN';

export const FILTER_SHOPS_SUCCESS = 'FILTER_SHOPS_SUCCESS';
